### PR TITLE
OWTimeSlice: Spring cleaning

### PR DESCRIPTION
**Pull request by irgolic**
This PR rebases off #94.

##### Description of changes
- [x] Fix step size after adjusting the time window with a datetime edit (as opposed to grabbing and moving the sliders)
- [x] Smart selection (discretize according to time delta, constrict slider range according to `(max time - min time) / time delta`)
- [x] Make new selection on click(+drag) outside of the area between the sliders
- [x] Set a timer (using the specified interval) for sending data while moving the time window
- [x] Change Overlap Setting to Step size Setting

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by irgolic** [comment]
There's some room for optimization, there's a lot of datetime objects being instantiated – these could be cached in, say, _TimeSliderMixin.

Also, there's some weird stuff going on with repainting. A call to `update` won't trigger a repaint, but a call to `repaint` will (I assume it's a repainting issue because if you cover the window with another window, and uncover it, the widget is properly repainted). I hotfixed this with three calls to `repaint`.

**Comment by robertcv** [comment]
Hey @irgolic ! I have an issue with our covid-19 dataset. Try [time_slice.zip](https://github.com/biolab/orange3-timeseries/files/4443097/time_slice.zip) workflow. For me, the time slicer stops at 2020-03-29 and does not work beyond this date.

**Comment by robertcv** [comment]
I glanced at your code and it seems fine. My only complaint is the exception in line [475](https://github.com/biolab/orange3-timeseries/pull/89/files#diff-6f961a70cdbf12bdd971393106c97274R475). No widget should explicitly call an exception. I suggest you replace it by showing an Error.

**Comment by robertcv** [comment]
The widget crashes when removing input while slicing data. The following error continues to flash:
```
Traceback (most recent call last):
  File "/home/robert/git/orange3-timeseries/orangecontrib/timeseries/widgets/owtimeslice.py", line 335, in play_single_step
    minValue = min(new_value(minValue), self.slider.maximum())
  File "/home/robert/git/orange3-timeseries/orangecontrib/timeseries/widgets/owtimeslice.py", line 319, in new_value
    return self.slider.unscale(newTime.timestamp())
  File "/home/robert/git/orange3-timeseries/orangecontrib/timeseries/widgets/owtimeslice.py", line 74, in unscale
    (self.maximum() - self.minimum()) /
TypeError: unsupported operand type(s) for -: 'float' and 'datetime.datetime'
```

**Comment by irgolic** [comment]
> I glanced at your code and it seems fine. My only complaint is the exception in line [475](https://github.com/biolab/orange3-timeseries/pull/89/files#diff-6f961a70cdbf12bdd971393106c97274R475). No widget should explicitly call an exception. I suggest you replace it by showing an Error.

I want it to raise an exception, so that if somebody's working with timedeltas of >= 100 years, they can send a report. That way we'll know it's a use case.

**Comment by robertcv** [comment]
I get an exception for data with missing values:
```
Traceback (most recent call last):
  File "/home/robert/git/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/home/robert/git/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/home/robert/git/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/home/robert/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/home/robert/git/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/home/robert/git/orange3-timeseries/orangecontrib/timeseries/widgets/owtimeslice.py", line 381, in set_data
    min_dt = datetime.datetime.fromtimestamp(round(time_values.min()), tz=datetime.timezone.utc)
ValueError: Invalid value NaN (not a number)
```

**Comment by irgolic** [comment]
If you plug an As Timeseries widget in between, it'll appropriately throw an error due to the NaNs. The problem's related to #85, in which an As Timeseries widget is implied (the conversion to timeseries is automatic), but it doesn't behave exactly the same (the timeseries is not sorted, and therefore not checked for NaNs).

**Comment by ajdapretnar** [comment]
Very much against discrete windows. Conceptually it is not correct. Please compare below.
Master:
master

PR:
pr

Widget should display progression and also never output empty data as seems to do now.
Also, the widget crashes with custom step size.
Delay could be a slider with faster-slower. Msec seems overly precise.

**Comment by irgolic** [comment]
> I get an exception for data with missing values

Addressed in #95 

> Very much against discrete windows. Conceptually it is not correct. Please compare below.
> Widget should display progression and also never output empty data as seems to do now.
> Also, the widget crashes with custom step size.

This was done with the Yahoo Finances dataset, which only holds data for Monday-Friday, meaning it has several unique timedeltas. Timedelta is minimally refactored in #94. This PR bases off #94, and extends the new timedelta class with a 'minimum timedelta' attribute.

**Comment by robertcv** [comment]
Hey, I am still getting the missing values error from before.

**Pull request merged**
