### PR TITLE
Fix Yahoo Finance Import

### PR DESCRIPTION
**Pull request by rsfutch77**
##### Issue
Yahoo Finance does not work (see #256)

##### Description of changes
import new yfinance module

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by rsfutch77** [comment]
So I might have fixed it, but I haven't figured out how to build the whole Orange app yet to test it. My orange python environment still gives me this error:
`ModuleNotFoundError: No module named 'yfinance'`

**Comment by PrimozGodec** [comment]
@rsfutch77, thank you for the contribution. It looks good and is working. So, I will merge the fix. 
Probably, you got a `ModuleNotFoundError ` since the finance module was not installed. You should just call `pip install -e .` in a directory with this module, and all required packages will be installed.

**Comment by PrimozGodec** [comment]
And sorry for delay with review.

**Comment by rsfutch77** [comment]
Woohoo I just saw this in the release version! Thanks!

**Pull request merged**
