### PR TITLE
OWSpiralogram: allow inverting Y axis

### PR DESCRIPTION
**Pull request by kernc**
@ajdapretnar fixes https://github.com/biolab/orange3-timeseries/issues/16

### CODE REVIEW

**Comment by ajdapretnar** [comment]
I'd test and merge, but I don't have a write access and I don't know how to test it... 🙈

**Comment by kernc** [comment]
Re test, it should plot concentric circles in Y-inverted order.

**Comment by ajdapretnar** [comment]
Yes, but I don't see my super-handy git code underneath the PR. I'll try to do it manually....

**Comment by ajdapretnar** [comment]
It works. 👍

**Pull request merged**
