### PR TITLE
[WIP] [ENH] Add new datasets

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
Only one dataset available.

##### Description of changes
Add new datasets:

- ~Bitcoin price~
- NBA game scores
- NFL game scores
- US candy production
- stocks
- Daily Demand Forecasting Orders Data Set 
 https://archive.ics.uci.edu/ml/datasets/Daily+Demand+Forecasting+Orders

Sources:
- https://www.kaggle.com/datasets
- https://archive.ics.uci.edu/ml/datasets.html

##### Includes
- [ ] Code changes
- [ ] Tests
- [ ] Documentation
- [x] Datasets

### CODE REVIEW

**Comment by kernc** [comment]
9×👎 on bitcoin data. Has more issue than is worth.

Candy only has a single variable, like airpassengers.

These datasets aren't visible/used anywhere.

**Comment by jerneju** [comment]
@kernc:

> These datasets aren't visible/used anywhere.

So we need another open dataset widget? Like in **Core** and in **Text**?

**Comment by kernc** [comment]
-1 on that too since time series is no different than a regular dataset.

**Comment by kernc** [comment]
I don't understand the issue here.

What's the problem with "only one dataset available?" How does this PR address the issue in practice, other than filling the _datasets_ folder. How is the user affected?

**Comment by kernc** [comment]
I think additional datasets would fit rather in https://github.com/biolab/datasets.

**Comment by jerneju** [comment]
> What's the problem with "only one dataset available?" How does this PR address the issue in practice, other than filling the datasets folder. How is the user affected?

The only problem is that widgets cannot be run alone because some datasets are unavailable. For instance, datasets _yahoo_MSFT_, _yahoo1_, _UCI-SML2010-1_, _yahoo_, and _autoroute_ are missing.

I just wanted to replace these datasets with some new ones.

> I think additional datasets would fit rather in https://github.com/biolab/datasets.
Ok, should I move _airpassengers_ to that folder?

**Comment by kernc** [comment]
So we already have _airpassengers_; why not use that in `__main__`?

And add the rest to Datasets if you will. But with Datasets, IIUC, it's important that they have a certain story, something interesting that makes them appropriate as an easily accessible showcase examples.

**Pull request closed without merging**
