### PR TITLE
[ENH] Moving transform: Add context settings

### PR DESCRIPTION
**Pull request by janezd**
Add context settings for Moving Transform.

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by janezd** [comment]
@AndrejaKovacic, I think this is OK now. Can you test it?

**Comment by AndrejaKovacic** [comment]
It seems to work as expected :)

**Comment by janezd** [comment]
If anybody cares to study context handlers, (s)he's welcome to review and merge. If nobody does it until Friday morning, I'll take @AndrejaKovacic's word for it and merge it myself. :)

**Comment by ajdapretnar** [comment]
This looks good to me.

**Pull request merged**
