### PR TITLE
OWDifference: remember selected attributes

### LINKED ISSUE #75: Difference widget loses selected column names after upstream change or saving and reopening workflow file
##### Timeseries version
0.3.3

##### Orange version
3.23.1

##### Expected behavior
After upstream changes in the workflow, the Difference widget should check if the selected columns still exist, and keep those selected columns that are still available.
After saving and reopening the .ows file, the Difference widget should check if the selected columns still exist, and keep those selected columns that are still available.

##### Actual behavior
After upstream changes in the workflow, the Difference widget forgets which columns were selected. These have to be manually reselected.
After saving and reopening the .ows file, the Difference widget  forgets which columns were selected. These have to be manually reselected.

This is annoying: the whole point of having and saving a workflow is, that it can be reused without having to redefine parts of it.

##### Steps to reproduce the behavior
Select columns to be differentiated in the Difference widget, then make upstream changes to the workflow. Re-check the selection in the Difference widget.
Select columns to be differentiated in the Difference widget, then save the workflow file and re-open it. Re-check the selection in the Difference widget.

### PR DESCRIPTION
**Pull request by ajdapretnar**
##### Issue

Fixes #75. 

##### Description of changes
Save selection in OWDifference.
Add tests.

~TODO: Consider moving select_rows to utils in Orange and import from there.~

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by nikicc** [comment]
# [Codecov](https://codecov.io/gh/biolab/orange3-timeseries/pull/79?src=pr&el=h1) Report
> Merging [#79](https://codecov.io/gh/biolab/orange3-timeseries/pull/79?src=pr&el=desc) into [master](https://codecov.io/gh/biolab/orange3-timeseries/commit/eb76eb249858ac3ada0a56230b1a318348fee49c&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/biolab/orange3-timeseries/pull/79?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master      #79   +/-   ##
=======================================
  Coverage   67.51%   67.51%           
=======================================
  Files           7        7           
  Lines         671      671           
  Branches      102      102           
=======================================
  Hits          453      453           
  Misses        173      173           
  Partials       45       45           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/biolab/orange3-timeseries/pull/79?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/biolab/orange3-timeseries/pull/79?src=pr&el=footer). Last update [eb76eb2...318ecc6](https://codecov.io/gh/biolab/orange3-timeseries/pull/79?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by ajdapretnar** [comment]
Waiting for https://github.com/biolab/orange3/pull/4453.

**Comment by ajdapretnar** [comment]
Ready to review and merge.

**Comment by PrimozGodec** [comment]
A problem with this solution appears when the order of attributes changes in a domain or one variable before the selected variable is removed. In this case, the wrong variable is selected. The easiest way to reproduce this issue is to use the Select columns before the Difference widget and then change the order of the selected variable in the Select columns widget. The problem is that the selection is remembered as a list of indexes but the order of variables can change or one variable is removed but still the same context is restored since the domain is similar.

Better would be to remember selection by the variable names.

**Comment by ajdapretnar** [comment]
> A problem with this solution appears when the order of attributes changes in a domain or one variable before the selected variable is removed. 

Agree, but this is the same with Correspondence Analysis and Rank and Feature Statistics, all of which enable selecting several attributes. I cannot decide what is the best way to go about this, since model only stores indices. I can do a name: index mapping, but it just somehow seems like a bad hack. Ideas?

**Comment by ajdapretnar** [comment]
Nevermind. Figured it out, but the code is now a bit messy. Got to convert back and forth to still be able to use select_rows() function. You can check now @PrimozGodec.

**Comment by PrimozGodec** [comment]
It is good now. :) It currently does not work with the Orange release. Do we merge this PR anyway? In this case, it need to be made sure that the addon is not released before orange is released.

**Comment by janezd** [comment]
We did the same on geo add-on: we merged PRs that require master, but we'll wait with the release.

**Pull request merged**
