### PR TITLE
 Line Chart: Remake

### LINKED ISSUE #109: Line Chart missing outputs
##### Timeseries version
Orange3-Timeseries 0.3.6

##### Orange version
Orange3 3.25.0

On Windows 10 64 Bit

##### Expected behavior
Expect to see High (Forecast), High (Forecast; 95% CI Lower), & High (Forecast; 95% CI Upper) label with their respective line graphs   

##### Actual behavior
Only get High (Forecast) & High (Forecast; 95% CI) in label with line graphs for High (Forecast) & High (Forecast; 95% CI). High (Forecast; 95% CI) represents the Lower 95%.

##### Steps to reproduce the behavior
Construct Example as shown, check out Line Chart for "High" and for other variables

### PR DESCRIPTION
**Pull request by VesnaT**
##### Issue

Replace highcharts with pyqtgraph.
Fixes #109, #158, #215

##### Description of changes
Write the widget from scratch.

##### TODO
- [x] I'd make the lines thicker. They are difficult to see, even at my young age. :)
- [x] I LOVE the tooltip, but it shows strange numbers. For Yahoo Finance, it mostly shows 14 decimal places, even though the original data have at most 4.
- [x] I'd put the legend below the chart. The actual data can be high enough to partially obscure the legend, especially when using "area". Or if not below the chart, I'd make it at least semi-transparent and moveable.
- [x] This is very minor, but the charts don't seems to be aligned. I mean they are aligned vertically, the tooltip is correct and the ticks are ok, it's just the beginning of the chart that seems off. But again, nothing major.
- [x] Currently, I can add as many plots as I want. Before, we limited them to 5, which is about what can fit on a regular ~30'' monitor.
- [x] When there's more than one data instance in a given period (for example, 3 instances on a single day), the chart gets strange. The line shows max, but the tooltip seems to show a random instance (not max). We should discuss and decide what to do in this case. This is also the case when the data is highly granular. Hours are apparently "aggregated" to a few steps (i.e. 10:00, 13:00, 16:00, 19:00), but the data still shows everything. So sometimes it is impossible to go over the max value with the tooltip, even though it is shown in the chart.
- [x] Column option sometimes doesn't show any plot. Use "Illegal waste dumpsites in Slovenia", attribute "Distance from road".

##### Former features that we should consider:
- [x] Currently, there is a continuous line, even when the data for a given period is missing. This is probably misleading and/or not desired? I personally like it, but I am unsure how accurate it is. We should discuss how to consider gaps in timeseries. As nan (not plotting them or plotting a grey dotted line)? When there's an explicit nan (date is given and the attribute value is nan), the line is missing in those places.

##### Features that I think would be amazing to have at some point:
- [ ] zoom (when there are lots of data, forecast can be almost invisible on a chart). We need to discuss how to implement this. Do all charts zoom in in-sync? Do we force zoom when there's forecast on the input? Disable other charts? Disable zoom if more than one chart present?
- [ ] subgroup

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
This feels like a Christmas morning to me. ❤️

**Comment by ajdapretnar** [comment]
A few minor comments:
- I'd make the lines thicker. They are difficult to see, even at my young age. :)
- I LOVE the tooltip, but it shows strange numbers. For Yahoo Finance, it mostly shows 14 decimal places, even though the original data have at most 4.
- I'd put the legend below the chart. The actual data can be high enough to partially obscure the legend, especially when using "area". Or if not below the chart, I'd make it at least semi-transparent and moveable.
- This is very minor, but the charts don't seems to be aligned. I mean they are aligned vertically, the tooltip is correct and the ticks are ok, it's just the beginning of the chart that seems off. But again, nothing major.
- Currently, I can add as many plots as I want. Before, we limited them to 5, which is about what can fit on a regular ~30'' monitor.
- When there's more than one data instance in a given period (for example, 3 instances on a single day), the chart gets strange. The line shows max, but the tooltip seems to show a random instance (not max). We should discuss and decide what to do in this case.
- Column option sometimes doesn't show any plot. Use "Illegal waste dumpsites in Slovenia", attribute "Distance from road".

Former features that we should consider:
- zoom (when there are lots of data, forecast can be almost invisible on a chart). We need to discuss how to implement this. Do all charts zoom in in-sync? Do we force zoom when there's forecast on the input? Disable other charts?
- Currently, there is a continuous line, even when the data for a given period is missing. This is probably misleading and/or not desired? I personally like it, but I am unsure how accurate it is. We should discuss how to consider gaps in timeseries. As nan (not plotting them or plotting a grey dotted line)? When there's an explicit nan (date is given and the attribute value is nan), the line is missing in those places.

Features that I think would be amazing to have at some point:
- subgroup!

**Comment by VesnaT** [comment]
Thank you for the detailed feedback. I'll look into that.

Regarding the line thickness: I agree the lines are not thick enough, but the problem is, that the pyqtgraph gets much slower, when the line's width is bigger than 1 (when there are many lines).

**Comment by ajdapretnar** [comment]
> Regarding the line thickness: I agree the lines are not thick enough, but the problem is, that the pyqtgraph gets much slower, when the line's width is bigger than 1 (when there are many lines).

😬 Bummer

**Comment by janezd** [comment]
Pyqtgraph uses `QPainter.drawPath` (https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/PlotCurveItem.py#L897), which is slow when plotting lines of width > 1 because of line joints etc (https://bugreports.qt.io/browse/QTBUG-27545). 

Pyqtgraph is aware of this. I also was correct (but only incidentally) that @markotoplak could be the person to ask about it.

Pyqtgraph made this faster in https://github.com/pyqtgraph/pyqtgraph/pull/2011 (by using `QPainter.drawLine`, as if painting with `connect="pair"`), but then slowed it down in https://github.com/pyqtgraph/pyqtgraph/pull/2185 if antialiasing is enabled and plotting by segments is not enabled specifically.

The solution is to set `segmentedLineMode` to `"on"`. This should be fast on any version of pyqtgraph that includes https://github.com/pyqtgraph/pyqtgraph/pull/2011.

**Pull request merged**
