### PR TITLE
Interpolate data according to time values

### LINKED ISSUE #136: Interpolation does not consider the time-variable
##### Timeseries version

0.3.7

##### Orange version

3.xx

##### Expected behavior
I would expect interpolation to take the time-distance from data-entries into account.
For the given example, this would mean that the interpolated values would be 16, 18, 20.

##### Actual behavior
Interpolation is independent on the timevariable distance.
This results in wrong interpolation values for irregular timed entries.

##### Steps to reproduce the behavior
Use the provided Dataset and Interpolation widget.

##### Additional info (worksheets, data, screenshots, ...)
data
interp_sp

### PR DESCRIPTION
**Pull request by WolfgangK1MET**
##### Issue
Fixes #136 

##### Description of changes
- changed x value for interpolation from array position to actual time_value.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by kernc** [comment]
The change seems to [break CI](https://travis-ci.org/github/biolab/orange3-timeseries/jobs/739235926#L867-L885):
```
Traceback (most recent call last):
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/tests/test_seasonal.py", line 12, in test_seasonal_decomposition
    decomp = seasonal_decompose(data[:, data.domain.class_var], model='multiplicative')
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/functions.py", line 393, in seasonal_decompose
    interp_data = data.interp()
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/timeseries.py", line 254, in interp
    self._interp_multivariate)
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/functions.py", line 274, in interpolate_timeseries
*   _x = Timeseries(data).time_values.astype(float)
  File "/home/travis/build/biolab/orange3-timeseries/orangecontrib/timeseries/timeseries.py", line 207, in time_values
    return self.get_column_view(self.time_variable)[0]
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/Orange/data/table.py", line 1106, in get_column_view
    col_index = self.domain.index(index)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/Orange/data/domain.py", line 361, in index
    raise ValueError("'%s' is not in domain" % var)
ValueError: 'Month' is not in domain
```
@ajdapretnar any clues?

**Comment by ajdapretnar** [comment]
`decomp = seasonal_decompose(data[:, data.domain.class_var], model='multiplicative')`

`seasonal_decompose` is passed `data[:, data.domain.class_var]`, which does not contain any time values, but `data.time_variable` remain untouched (remembers it). So in `_x = Timeseries(data).time_values.astype(float)`, Timeseries sees the time_variable attributes and tries to use it, but without success.

You can set time_variable to None before `decomp`, perhaps.

**Comment by kernc** [comment]
> `data[:, data.domain.class_var]`, which does not contain any time values, but `data.time_variable` remain untouched (remembers it)

But is it appropriate to remedy an inconsistent internal state somewhere externally?

Shouldn't validity of `.time_variable` be _asserted_ already in `from_data_table()`, which all other constructions use:
https://github.com/biolab/orange3-timeseries/blob/f4f7934f6cc55774342cce46ad2f1fef7c692cfd/orangecontrib/timeseries/timeseries.py#L102-L140
or even as late as:
https://github.com/biolab/orange3-timeseries/blob/f4f7934f6cc55774342cce46ad2f1fef7c692cfd/orangecontrib/timeseries/timeseries.py#L209-L213
?

**Comment by ajdapretnar** [comment]
I was thinking about this for some time. Sure it could be. It probably should. I am just skeptical, because `data[:, data.domain.class_var]` is a direct botch of the Timeseries object and not something that can 'just happen'.

**Comment by kernc** [comment]
Could be `data[indices, :]` or `data[:, subset_columns_sans_timevar]` and just as valid. Isn't that how one does a normal column-wise subset selection? :stuck_out_tongue_closed_eyes:

**Comment by ajdapretnar** [comment]
Yes, but you created a Timeseries object and ripped out the time. 😆 No wonder it's bleeding all over the place.

I'll add an if clause to Timeseries and set the time_variable to None there.

**Comment by ajdapretnar** [comment]
I've made a PR in #143. However, this PR will have to be modified to `_x = Timeseries.from_data_table(data).time_values.astype(float)`. Just calling Timeseries won't work.

**Comment by WolfgangK1MET** [comment]
Ty guys, I've changed the fix to match PR #143

**Comment by ajdapretnar** [comment]
Now that #143 has been merged, you'd probably have to rebase to master. While doing it, it would also be nice to squash the commits to have a single commit for this PR in the commit history.
First, make sure you have the latest master. Then run
`git rebase -i master`
This will open vim with all the commits. Move up to the second commit. Press `i` to enter the interactive mode. Change pick to `fixup` or `f`. Do this for 2nd and 3rd commit. Press Esc to exit interactive mode. Then type `:wq`, which will save the state. Finally, run `git push -f origin develop`, where `develop` is the name of this branch.

**Comment by kernc** [comment]
@ajdapretnar :astonished: Fyi, maintainers can ["Squash and merge" PRs on GitHub](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request#merging-a-pull-request-on-github). Works quite well.

**Comment by ajdapretnar** [comment]
😮 🤯

**Comment by ajdapretnar** [comment]
But it does not enable rebasing, squashing and merging. 😞 @WolfgangK1MET You can just rebase, I will squash and merge. (rebasing is done with `git rebase master`, then pushing to this branch)

**Comment by WolfgangK1MET** [comment]
I tried, but somehow I can't do it. (Using Git bash under windows)
For one, there are no commit entries, when i open the rebase in my editor. There is only a single "noop" and then a bunch of comments.
And secondly, I'm asked to sign in when i try to push, but the login always fails.
But that may be because i somehow have to use 2 different git-accounts on my work-laptop without any admin-rights to easily swap between accounts ... (quite complicated, dont ask why, IT said, I cant do it otherwise, and I just gave up on refusing them ...) 
I'll try everything again, when I'm back home.
Thx for your help and your patience :)

**Comment by WolfgangK1MET** [comment]
> Now that #143 has been merged, you'd probably have to rebase to master. While doing it, it would also be nice to squash the commits to have a single commit for this PR in the commit history.
> First, make sure you have the latest master. Then run
> `git rebase -i master`
> This will open vim with all the commits. Move up to the second commit. Press `i` to enter the interactive mode. Change pick to `fixup` or `f`. Do this for 2nd and 3rd commit. Press Esc to exit interactive mode. Then type `:wq`, which will save the state. Finally, run `git push -f origin develop`, where `develop` is the name of this branch.

ok, so i just did everything according to your instructions. 
now i was able to change the pick entries to fixup.
hopefully everything is now as it is intended.
thx for your guidance :)

**Comment by ajdapretnar** [comment]
Beautiful, thanks! I'll merge as soon as the tests pass.

**Pull request merged**
