### PR TITLE
OWTimeSlice: Handle numeric time delta

### LINKED ISSUE #110: Time Slice: crashes with missing values
##### Timeseries version

0.3.6

##### Orange version

3.26.0.dev

##### Expected behavior
Time Slice works.

##### Actual behavior
Time Slice crashes with two different errors when data has missing values.

##### Steps to reproduce the behavior
1. Without As Timeseries.
```
----------------------------- TypeError Exception -----------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owtimeslice.py", line 409, in set_data
    maximum = round(range / delta)
TypeError: type datetime.timedelta doesn't define __round__ method

```

2. With As Timeseries.
```
------------------------- ZeroDivisionError Exception -------------------------
Traceback (most recent call last):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/Users/ajda/orange/orange-canvas-core/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owtimeslice.py", line 409, in set_data
    maximum = round(range / delta)
ZeroDivisionError: integer division or modulo by zero
-------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by irgolic**
##### Issue
Fixes #110 

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by irgolic** [comment]
I also pushed some cosmetic changes to time slice. Is there an easier way of achieving what I've implemented?

Also, I couldn't get the checkboxes to align, and there's more space below the controls within a box than above. With the fixed control area size, this has now become more apparent. I suppose this is an orange-widget-base issue though?

**Comment by ajdapretnar** [comment]
Now I get a different error:
```
Traceback (most recent call last):
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 936, in __process_next
    if self.__process_next_helper(use_max_active=True):
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 974, in __process_next_helper
    self.process_node(selected_node)
  File "/Users/ajda/opt/miniconda3/envs/o3/lib/python3.8/site-packages/orangecanvas/scheme/signalmanager.py", line 605, in process_node
    self.send_to_node(node, signals_in)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 792, in send_to_node
    self.process_signals_for_widget(node, widget, signals)
  File "/Users/ajda/orange/orange-widget-base/orangewidget/workflow/widgetsscheme.py", line 826, in process_signals_for_widget
    handler(*args)
  File "/Users/ajda/orange/orange3-timeseries/orangecontrib/timeseries/widgets/owtimeslice.py", line 535, in set_data
    slider.setMaximum(maximum + 1)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

Attaching the data for replicating it:
[00011 MP KARAVANKE - HRUŠICA.csv.zip](https://github.com/biolab/orange3-timeseries/files/4868790/00011.MP.KARAVANKE.-.HRUSICA.csv.zip)

**Comment by ajdapretnar** [comment]
Also, tests would be real nice to prevent such errors in the future. :)

**Comment by ajdapretnar** [comment]
I am still getting the `OverflowError`.

**Comment by irgolic** [comment]
> I am still getting the `OverflowError`.

Fixed by https://github.com/biolab/orange3-timeseries/pull/122.

**Comment by irgolic** [comment]
The test for this, which was previously in this PR, was moved to #125.

**Pull request merged**
