### PR TITLE
[FIX] Datetime and timestamp conversion on Windows

### LINKED ISSUE #47: Timestamp and datetime conversions may crash on Windows
Similar to https://github.com/biolab/orange3/issues/2828 .

##### Timeseries version
Since `datetime.fromtimestamp` and `dt.timestamp()` where `dt` is `datetime` is used.

##### Expected behavior
Function works on any platform.

##### Actual behavior
- `datetime.fromtimestamp(ts)` where `ts < 0`: `OSError` 
- `dt.timestamp()` where `dt.year < 1970`: `OverflowError`

##### Additional info (worksheets, data, screenshots, ...)
`OverflowError`: https://sentry.io/biolab/orange3-timeseries/issues/428467601/
`OSError`: https://sentry.io/biolab/orange3-timeseries/issues/393933243/

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
Fixes #47 .

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-timeseries/issues/428467601/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-timeseries/issues/393933243/

**Comment by kernc** [comment]
Tests for the new {from,}timestamp conversions.

**Comment by jerneju** [comment]
Trying to write a proper test. Mostly I got an an error message:

```py
TypeError: can't set attributes of built-in/extension type 'datetime.datetime'
```

**Comment by kernc** [comment]
So don't patch `datetime.datetime`, but `datetime` module instead?
```py
class my_datetime:
    def fromtimestamp(ts):
        ...

with patch('datetime.datetime', my_datetime):
    ...
```
Or
```py
import datetime
datetime.datetime = my_datetime
...
```

**Comment by kernc** [comment]
@jerneju Thanks. I still don't claim to understand it, but at least am now confident that it works for the cases tested. 😄

**Pull request merged**
